# Generated by Django 4.2.27 on 2025-12-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default='Lecturer', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Academic', 'Academic Staff'), ('Admin', 'Administrative Staff')], max_length=50),
        ),
    ]
