# Generated by Django 4.2.27 on 2025-12-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_department_college_program_course'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='summary',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('publication_type', models.CharField(choices=[('Journal', 'Journal Article'), ('Conference', 'Conference Paper'), ('Book', 'Book Chapter')], max_length=50)),
                ('journal_or_conference', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('doi_or_link', models.URLField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.department')),
                ('research_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='research.researchproject')),
            ],
        ),
    ]
